"""Migración inicial completa

Revision ID: 7ef568c8517f
Revises: 
Create Date: 2026-05-01 16:41:56.263137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef568c8517f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('ruta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pasos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('parada_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['parada_id'], ['paradas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pasos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pasos_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reset_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuarios_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_timestamp'))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('reset_code_expires')
        batch_op.drop_column('reset_code')
        batch_op.drop_column('rol')

    with op.batch_alter_table('pasos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pasos_timestamp'))

    op.drop_table('pasos')
    op.drop_table('paradas')
    # ### end Alembic commands ###
